---
- name: Install Nginx
  pacman:
    name: nginx-mainline
    state: present

- name: Install Nginx configuration file
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: "reload nginx"

- name: Generate Diffie-Hellman parameter
  shell:
    cmd: openssl dhparam -out dhparams.pem 4096
    creates: /etc/nginx/dhparams.pem
  notify: "reload nginx"

- name: Ensure /etc/nginx/conf.d exists
  file:
    path: /etc/nginx/conf.d
    owner: root
    group: root
    mode: 0755
    state: directory
  notify: "reload nginx"

- name: Ensure /etc/nginx/sites-available exists
  file:
    path: /etc/nginx/sites-available
    owner: root
    group: root
    mode: 0755
    state: directory
  notify: "reload nginx"

- name: Ensure /etc/nginx/sites-enabled exists
  file:
    path: /etc/nginx/sites-enabled
    owner: root
    group: root
    mode: 0755
    state: directory
  notify: "reload nginx"

- name: Install Nginx virtual hosts
  copy:
    src: "{{ vhost_location }}/{{ item }}"
    dest: /etc/nginx/sites-available/
    owner: root
    group: root
    mode: 0644
  loop: "{{ vhosts }}"

- name: Enable nginx service
  systemd:
    name: nginx
    enabled: true
    state: started
    daemon_reload: true
